language: go

go:
  - "1.16"

before_install:
  - go get -t -v ./...

script:
  - go test ./... -coverprofile coverage/coverage.txt

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage/coverage.txt